name: CI

# Controls when the action will run.
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-android:
    name: Android ${{ matrix.host }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        host: [aarch64-linux-android]

    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - run: ./native/libffi/.ci/install.sh
      - env:
          HOST: ${{ matrix.HOST }}
          ANDROID_API_LEVEL: 24
          CONFIGURE_OPTIONS: "--disable-multi-os-directory" # fixes warning about unsupported -print-multi-os-directory with clang
        run: |
          ./android_ci_build.bash
      - uses: actions/upload-artifact@v4
        with:
         name: artifact
         path: libs
