# Full CI matrix on all pushes to master branch, and all PRs
name: Java CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]
      # Run all tests even if one fails
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Linux requirements
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get -y install texinfo
      - name: Build with Ant
        run: |
          ANT_OPTS="-D-Dos.prefix=aarch64-android -Dos.arch=aarch64"
          export ANT_OPTS
          ant test
          ant test-platform

